#!/bin/bash

set -e

SCRIPT_DIR=$( cd -- "$( dirname -- "${0}" )" > /dev/null 2>&1 && pwd )

. "${SCRIPT_DIR}/dx.sh.lib"

require_command "docker"

usage_on_help "Builds the Docker image based on the Dockerfile" "" "${@}"
ensure_docker_compose_env

if [[ -f "${SCRIPT_DIR}/build.pre" && -x "${SCRIPT_DIR/build.pre}" ]]; then
  log "🎬" "${SCRIPT_DIR}/build.pre exists - executing"
  "${SCRIPT_DIR}/build.pre" Dockerfile.dx "${IMAGE}"
fi
docker build -f Dockerfile.dx -t "${IMAGE}" ./

log "🌈" "Your Docker image has been built tagged '${IMAGE}'"
log "🔄" "You can now run dx/start to start it up, though you may need to stop it first with Ctrl-C"

if [[ -f "${SCRIPT_DIR}/build.post" && -x "${SCRIPT_DIR/build.post}" ]]; then
  log "🎬" "build.post exists - executing"
  "${SCRIPT_DIR}/build.post" Dockerfile.dx "${IMAGE}"
fi
log "✅" "Done"

# vim: ft=bash
