#!/bin/bash

set -e

SCRIPT_DIR=$( cd -- "$( dirname -- "${0}" )" > /dev/null 2>&1 && pwd )

. "${SCRIPT_DIR}/dx.sh.lib"
require_command "docker"

usage_on_help "Starts all services, including a container in which to run your app" "" "${@}"
ensure_docker_compose_env

log "🚀" "Starting docker-compose.dx.yml"

BUILD=--build
if [ "${1}" == "--no-build" ]; then
    BUILD=
fi

docker compose -f docker-compose.dx.yml -p "${PROJECT_NAME}" --env-file "${ENV_FILE}" up ${BUILD} --timestamps --force-recreate

# vim: ft=bash
