require 'gli/option_parser_factory.rb'
require 'gli/gli_option_parser.rb'
require 'gli/app_support.rb'
require 'gli/app.rb'
require 'gli/command_support.rb'
require 'gli/command.rb'
require 'gli/command_line_token.rb'
require 'gli/command_line_option.rb'
require 'gli/copy_options_to_aliases.rb'
require 'gli/exceptions.rb'
require 'gli/flag.rb'
require 'gli/options.rb'
require 'gli/switch.rb'
require 'gli/dsl.rb'
require 'gli/version.rb'
require 'gli/commands/help'
require 'gli/commands/compound_command'
require 'gli/commands/initconfig'

module GLI
end
